name: Keep Active

on:
  schedule:
    - cron: "0 0 */15 * *"  # 每15天运行一次
  workflow_dispatch:

env:
  PAT: ${{ secrets.PAT }}
  USER: ${{ secrets.USER }}
  REPO: ${{ secrets.REPO }}

jobs:
  run-automation:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        persist-credentials: false

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install jinja2 python-dotenv

    - name: Run bludweb.py script
      run: python templates/bludweb.py webs 99
      env:
        PAT: ${{ secrets.PAT }}
        USER: ${{ secrets.USER }}
        REPO: ${{ secrets.REPO }}

    - name: Debug output
      run: |
        echo "Listing files in 'webs' directory:"
        ls -la webs || echo "Directory not found"
        cat webs/* || echo "No files"

    - name: Push changes manually
      env:
        TOKEN: ${{ secrets.PAT }}
        USER: ${{ secrets.USER }}
        REPO: ${{ secrets.REPO }}
      run: |
        git config --global user.name "${USER}"
        git config --global user.email "${USER}@users.noreply.github.com"
        
        # 设置远程地址，使用 PAT 认证
        git remote set-url origin https://x-access-token:${TOKEN}@github.com/${USER}/${REPO}.git
        git remote -v
        
        git add .
        git commit -m "🤖 Auto update [skip ci]" || echo "Nothing to commit"
        
        # 尝试拉取远程更改以避免冲突
        git pull origin main --rebase || { echo "Rebase failed. Attempting force push..."; git push --force origin main; exit 0; }
        
        # 推送更改，如果推送失败则强制推送
        git push origin main || { echo "Push failed. Attempting force push..."; git push --force origin main; }
      shell: bash
